lunafromthemoon/RenJS-V2

src/core/RJS.ts
=> fix: `resolveAction` scope lost when assigning to `control`

src/managers/BackgroundManager.ts
partial fix for #32 
OK i think i have a slightly better understanding of the bug here: there's a few different performance optimizations in Phaser which are interfering with positioning logic. The bounds are only updated during rendering, which means anything that references the bounds (e.g. positioning) will be incorrect on the frame that they are created unless you explicitly call `updateTransform()`.
In addition to that, `updateTransform` includes a check for visibility and early returns instead of actually updating the transform if the object is hidden, so in a case like this, the order needs to specifically be:
```js
const thing = thing.create();
thing.updateTransform();
thing.visible = false;
```
To test this one, I found that you can pretty easily repro the bg flicker with a …
=> fix: background flickering for one frame when shown

dev-only/story/Config.yaml, src/core/UserPreferences.ts
Currently, the `setPreferences` call goes through preferences passed in as a parameter and sets the values on `this.preferences`, but if one does not already exist on the class member, it will error out due to trying to access `.value` of `undefined`. This changes it to loop through the current preferences, and only try to apply the ones also found on the parameter.
Also removed the `voicesv` preference from the config in the test stories (it's unused and what prompted the error).
=> fix: issue where game crashes on init due to unknown preference

.github/workflows/branch.yml, README.md, package.json, webpack.dev.js
No user-facing changes, just some minor cleanup for devs
- cleans up some formatting issues in readme
- corrects license field in `package.json` to match `LICENSE.md`
- adds very basic github actions workflow to run lint + build on PRs
- an example run can be found here: https://github.com/seleb/RenJS-V2/runs/4056621793?check_suite_focus=true
- there are hundreds of unresolved lint errors atm (though many can be autofixed), so this check will be expected to fail until a full lint pass is done, but can still be useful on PRs to make sure that new code is being linted
- removed redundant clean plugin in webpack dev config
note: it seems like the existing build script only works on linux, but not sure why; it looks like it should work cross-platform but the copy bit always fails
=> Dev-facing cleanup

src/managers/LogicManager.ts
fixes #33
includes an empty array as choice actions if there are none when parsing to avoid errors downstream
=> fix: choice without action throwing error

src/screen-effects/Effects.ts
fixes #31 
Ensures the first line of the credits roll is formatted properly by replacing it with a space, and rendering the first line of text the same way as all the others.
Also makes a minor type safety improvement.
=> fix: markup on first line of credits rendered as text

src/gui/elements/ChoiceHandler.ts, src/gui/elements/Label.ts, src/gui/elements/MessageBox.ts, src/gui/elements/NameBox.ts, src/screen-effects/Effects.ts
Attempt at improving issues described in #32.
This definitely doesn't totally resolve the issues (doesn't even touch the images part), but it does seem to reduce the flicker on the namebox/dialogue. I'm still not 100% sure what the root cause is, but it seems to be a bug in Phaser's implementation of text bounds: if you remove the `boundsAlign` properties from the config. the flicker goes away entirely. I did find a seemingly related issue on their repo (https://github.com/photonstorm/phaser-ce/issues/518) but unfortunately it looks like it was closed without any particular resolution.
I tested by including the following at the top of `NameBox.show`:
```ts
requestAnimationFrame(() => {
requestAnimationFrame(() => {
debugger;
});
});
```
Prior to this change, the `debugger` would catch the …
=> fix: update text displays immediately when changing text

src/gui/elements/MaskSlider.ts
Refactors the slider to fix an issue similar to #32 where the slider fill flickers out for a single frame when changing value. Also adds a draggable mode.
This one had a few TS errors and other issues which made it difficult to debug, so it's a bit of a larger rewrite than the other fixes. I'm not sure if the old click-only behaviour needed to be kept around, so there's an extra `draggable` bool which can be switched to false by default if needed.
=> refactor slider

src/core/actions/StoryActionHide.ts, src/managers/BackgroundManager.ts
fixes #29
Cleans up the typescript in the background manager, and fixes issue where promise chain gets stuck in a state it can't resolve due to trying to hide a background that isn't currently shown. Trying to hide a background which is not the current one will now do nothing, allowing the game to continue. The behaviour for hiding any bg regardless of what name was passed in is still supported, but only for explicitly passing in a falsey name.
Also fixes bug in "hide all" where transition wasn't respected due to incorrect parameters being passed in.
=> fix: calling `hide` on a background freezing game

src/gui/RJSHUD.ts, src/utils/gui.ts
fixes #34
The order of HUD elements is currently defined by the GUI config, which results in choices being rendered underneath dialogue if both are on screen. This adds a sort to the GUI config before the elements are created to help avoid overlap issues.
=> fix: interactive elements rendered underneath dialogue

src/gui/elements/MaskSlider.ts
noticed that the `Pointer.pointerId` and `PointerEvent.pointerId` on firefox specifically are inconsistent, with one being `0` and the other being `null`; this defaults them to `0` to avoid `onEnd` never being called
=> fix: slider not releasing on firefox

src/states/Boot.ts
fixes another minor flicker issue noticed while debugging fonts (which may be exaggerated by the font fix): the "boot" state shows a copy of the loading screen, but never sets the loading bar, so it shows the bar full for a brief period before starting over at zero for the "preload" state
=> fix: loading screen starting full before starting at zero

package-lock.json, package.json, src/states/Boot.ts, src/states/PreloadStory.ts
Adds font preloading via `fontfaceobserver` and some slightly hacky manipulation of the phaser loader file list to make sure font loading is included as part of preload state + loading bar. Replaces previous font preload strategy where fonts were assumed to be loaded by rendering off-screen text during boot.
includes a refactor of the fix in #27 that adds bold + italic to preloaded fonts (note that oblique has been removed since renjs doesn't actually support oblique in the story markup).
=> fix: font preloading

src/gui/RJSGUI.ts
this appears to be a type notation that was unintentionally written as a default value, creating `RJSGUI.menus.string` as a reference to the `RJSMenu` class instead of defining the type of `RJSGUI.menus`
note: caught this in a lint pass, but it's a functional change so putting it up as a separate PR
=> fix: `RJSGUI.menus` being incorrectly initialized due to typescript error

src/gui/RJSGUIByBuilder.ts
this only affects older js, but can cause issues in parsing: `parseInt` used to automatically parse as octal if the number string started with a zero, so it's recommended to always specify the radix
note: caught this in a lint pass, but it's a functional change so putting it up as a separate PR
=> fix: fix missing radix when parsing thumbnail properties

package.json
npm seems to prefer the short form; fixes a warning on install:
```sh
npm WARN renjs@2.3.2 license should be a valid SPDX license expression
```
=> chore: use SPDX license abbreviation instead of full text

dev-only/story/test/TestStory.yaml, src/utils/gui.ts, src/utils/textStyle.ts
refactors the text style to use a stack-based approach so that `(end)` tags will close the last opened style rather than having tags lookahead to find an `(end)` (i needed to refactor this so semantic html could be created on my a11y draft, and figured the ingame text style improvement would be worth pulling out as a separate change)
Note that the regex has been changed to be slightly more specific too so that invalid hex colours (i.e. ones which are not actually 0-f, or are not 3/6 digits long) will be ignored.
Example of a case this addresses (added to the demo):
```yml
- text: Text can have (color:red)color(end) too. With hex (color:#f593e6)this is pink(end). This is (italic)italic (color:red)and(end) red(end).
```
Before:
After:
=> stack-based text style

RenJSQuickstart/story/GUI.yaml, dev-only/story/GUI.yaml, dev-only/story/NewGUI.yaml, dev-only/story/i18n/en/GUI.yaml, dev-only/story/i18n/es/GUI.yaml, dev-only/story/multipleboxes/GUI.yaml, dev-only/story/test/TestStory.yaml, docs/examples/GUI.yaml, docs/examples/i18n/en/GUI.yaml, docs/examples/i18n/es/GUI.yaml, docs/examples/multiboxportraits/GUI.yaml, docs/examples/tutorial/GUI.yaml, src/core/RJS.ts, src/gui/RJSGUI.ts, src/gui/RJSHUD.ts, src/gui/RJSMenu.ts, src/gui/a11y/Accessibility.ts, src/gui/elements/ChoiceHandler.ts, src/gui/elements/MessageBox.ts, src/gui/elements/NameBox.ts, src/gui/elements/RJSLoadingScreen.ts, src/states/Boot.ts, src/utils/textStyle.ts
fixes #37 
First pass at adding a mostly-invisible accessibility layer on top of the game canvas to support keyboard navigation and screen-reading. All interactive elements including choices, visual choices, menu buttons, sliders, and a text container have corresponding DOM elements which are updated to match their labels, positions, and interactions. These elements have inline CSS applied which allows their focus outline to be seen (except the text), but keeps the rest of the element hidden.
Screen-reading tested with [NVDA](https://github.com/nvaccess/nvda).
Known issues:
- The default tab navigation order won't always be visually intuitive: the DOM elements will be in the same order as the GUI element definitions. Previously, the save menu's "return" button was first instead of last, …
=> add accessibilty layer

src/gui/a11y/Accessibility.ts
avoids issues caused by the accessible labels assigning text using `innerHTML` in order to parse the tags added as part of the tokenization process
=> fix(a11y): escape html before tokenizing it for accessible label

src/gui/elements/MessageBox.ts, src/managers/LogicManager.ts, tsconfig.json
:wave: I was trying to work on some tooling for my VN using the codebase, and was getting turned around with the minimal use of type annotations.  I took a stab at adding improving the situation, which I'm splitting across multiple PRs to avoid flooding the project with changes.  I hope improvements to the typing of the codebase are welcome, as they've helped me understand the engine better.
---
This set of options guarantees:
* All functions that return a value actually do return a value
* `this` is associated with a specific type (not `any`)
* `call`/`bind`/`apply`ed functions are called correctly
* Function param and arg types match
Compliance with stricter type checks requires the following fixes:
* Fix incorrect return in `MessageBox.show`
* Tighten types on `LogicManager.choose` and …
=> Enable simple strict type checking options

src/core/RJS.ts
undefined managers was originally introduced in a refactor that had
code to `initModulesInOrder`; three of the managers could not be
calculated when following that code path. That code was never used and
has since been removed, but the optional manager typing remained.
Static analysis shows no place in the current code where a manager
could be undefined. By marking that in the type system, it simplifies
logic in other locations that would otherwise have to treat each
manager as optional.
=> Require all managers to be defined

docs/docs-page.html, src/core/RJS.ts, src/core/RJSTween.ts, src/gui/RJSHUD.ts, src/managers/AudioManager.ts, src/managers/BackgroundManager.ts, src/managers/CGSManager.ts, src/managers/CharacterManager.ts, src/managers/LogicManager.ts, src/managers/RJSManager.ts, src/managers/StoryManager.ts, src/managers/TweenManager.ts
Thank you for your time in looking at these changes.
I'm trying to work in manageable chunks to not spam the project with PRs.
---
Three changes are less trivial then just adding some typing code:
* The `AudioManager` works with specific types of audio that can be
typed with string literals (instead of arbitrary strings).
* `StoryManager.setupStory` deferred initialising some class properties
which allowed for potentially undefined values.
* Phaser is typed to accept "undefined" for unknown values, but was
getting passed "null" in some places.
Otherwise, it's pretty standard typing fixes, some of which make the
code more crash-resistant:
* Avoid performing math or calling methods on `undefined`
* Convert some objects ({}) to mapped types ({string:value})
* Assign custom types to …
=> Update managers to comply with strict typing

src/core/actions/StoryActionEffect.ts
should help in case where user typos an effect name
(this can be particularly confusing in the case of a `ROLLINGCREDITS` typo bc the game softlocks in addition to not playing the animation since it also relies on the effect to actually end the game)
=> fix: log unknown effects to console

src/core/RJS.ts, src/core/RJSGameConfig.ts, src/screen-effects/Effects.ts, src/screen-effects/Transition.ts
- fixes issue where `backgroundColor` is not actually applied
- makes credits automatically pick white or black based on contrasting against `backgroundColor` (previously would inherit the game's text style, which isn't necessarily legible since it has other GUI element sitting between it and the background)
- flags `backgroundColor` type as optional
note that there is a workaround for this rn, which is that you can wrap individual lines of your credits text with `color` tags; this should still work as an override for the automatic colour selection here
=> fix: credits/background colour issues
